import 'dotenv/config';

export default {
  expo: {
    name: "milkshop",
    slug: "milkshop",
    scheme: "milkshop",
    extra: {
      APPWRITE_ENDPOINT: process.env.APPWRITE_ENDPOINT,
      APPWRITE_PROJECT: process.env.APPWRITE_PROJECT,
      APPWRITE_PLATFORM: process.env.APPWRITE_PLATFORM,
      APPWRITE_API_KEY: process.env.APPWRITE_API_KEY,

      APPWRITE_DATABASE: process.env.APPWRITE_DATABASE, 
      ORDERS_COLLECTION: process.env.ORDERS_COLLECTION,
      CUSTOMERS_COLLECTION: process.env.CUSTOMERS_COLLECTION,
      PRODUCTS_COLLECTION: process.env.PRODUCTS_COLLECTION,
      USER_PRICE_COLLECTION: process.env.USER_PRICE_COLLECTION,
      SUBSCRIPTION_PLANS_COLLECTION: process.env.SUBSCRIPTION_PLANS_COLLECTION,
      SUBSCRIPTIONS_COLLECTION: process.env.SUBSCRIPTIONS_COLLECTION,
      ENTITLEMENTS_COLLECTION: process.env.ENTITLEMENTS_COLLECTION,

      APPLY_ENTITLEMENTS_FUNCTION_ID: process.env.APPLY_ENTITLEMENTS_FUNCTION_ID,
      ENTITLEMENTS_FUNCTION_ID: process.env.ENTITLEMENTS_FUNCTION_ID,
      BOOTSTRAP_USER_FUNCTION_ID: process.env.BOOTSTRAP_USER_FUNCTION_ID,
    }
  }
};
